# Specify the language and install dependencies
language: python
python:
  - "2.7"

# Install Ren'Py and navigate to the Ren'Py install directory
install:
  - cd ..
  - wget http://www.renpy.org/dl/7.3.2/renpy-7.3.2-sdk.tar.bz2
  - tar xf renpy-7.3.2-sdk.tar.bz2
  - rm renpy-7.3.2-sdk.tar.bz2
  - cd renpy-7.3.2-sdk

# Configure Ren'Py to not use ALSA to avoid ALSA dependency errors
env:
  - SDL_AUDIODRIVER=dummy

# Run the tests
script: ./renpy.sh "../Coyote-Creek/" lint && ./renpy.sh launcher distribute "../Coyote-Creek/"
